### ISSUE TITLE
Academy bugs

### ISSUE THREAD

**Issue by bf-monster** [betfinio/academy#32]
- [x] wrong answer is set as correct
![Image](https://github.com/user-attachments/assets/fda04251-23bc-405f-9bbe-65e420e08980)

- [x] not getting XP for correct answers
![Image](https://github.com/user-attachments/assets/2a9c1f5d-7c3a-4c24-9cb1-f736d0665eb2)

- [x] wrong links
https://betfin.network/academy/lesson/10/46 po splnění do odkazuje na https://betfin.network/academy/lesson/2/6 místo na další lekci v pořadí
https://betfin.network/academy/lesson/10/47 odkazuje po splnění na https://betfin.network/academy/lesson/10/41 místo na další v pořadí
https://betfin.network/academy/lesson/11/50 odkazuje zase jinam než by mělo
https://betfin.network/academy/lesson/13/56 odkazuje jinam než by mělo
https://betfin.network/academy/lesson/22/74 odkazuje jinam než by mělo
https://betfin.network/academy/lesson/17/99 chybí video a odkazuje to jinam
https://betfin.network/academy/lesson/23/79 špatně nastavená správná odpověď
https://betfin.network/academy/lesson/23/80 odkazuje na špatnou část akademie po dokončení
https://betfin.network/academy/lesson/24/83 odkazuje na špatnou část akademie po dokončení
https://betfin.network/academy/lesson/25/87 odkazuje na špatnou část akademie po dokončení
https://betfin.network/academy/lesson/26/89 špatně nastavená správná odpověď 
https://betfin.network/academy/lesson/26/92 odkazuje na špatnou část akademie po dokončení
https://betfin.network/academy/lesson/27/94 špatně nastavená správná odpověď
https://betfin.network/academy/lesson/27/95 odkazuje na špatnou část akademie po dokončení
https://betfin.network/academy/lesson/28/97 odkazuje na špatnou část akademie po dokončení

- [x] missing resources
Advanced—>affiliate:
![Image](https://github.com/user-attachments/assets/de1dc585-86eb-425a-8e8a-f8ff9fc43778)

update: I just spoke with Mike, the last point can be ignore. Please contact him directly, should there be any questions regarding this task

**Comment by bf-tom** [comment]
Update to the last @bf-mike-mkt Betfin Resources beong empty was reported twice this weeks, it is confusing. Therefore, either add some content to that or have it deleted entirely.

**Comment by bf-tom** [comment]
- [ ] change the text to TACKLE THE NEXT UNIT
![Image](https://github.com/user-attachments/assets/a50743dc-621f-43ed-819a-d6e20cdab432)

- [ ] To activate binary matching bonuses, you must stake a minimum amount of 120,000 BET tokens.

Delete the rest of the paragraph, please. 
![Image](https://github.com/user-attachments/assets/f80ac564-520b-43fe-8473-cec4189fafec)

- [ ] only one setion should be highlighted (the one I am in)
![Image](https://github.com/user-attachments/assets/0d90c04e-9e16-4f88-91df-8ad63d349b33)

**Comment by bf-tom** [comment]
he guys, is it on dev for testing? please share a link

**Comment by bf-monster** [comment]
betfin.dev/academy

**Comment by bf-tom** [comment]
there is one common issues. after answering some question correctly, I dont get confeti animation, XP and question are not ticked off. Instead, I can see the question is answer correctly and button chages to Next Questino. Which results in my academy looking unfinished:
![Image](https://github.com/user-attachments/assets/2fb93e01-bf87-45dc-875d-082c7bd18ce9)
 I can share the full list of affected questions if needed.

**Comment by bf-tom** [comment]
![Image](https://github.com/user-attachments/assets/21438e68-2461-4044-b96e-ab0d0923fe2b)
 This is wrong. Please change it to:

Stakers will received no rewards for the cycle and might lose some of their staked tokens.

**Comment by bf-monster** [comment]
@bf-plane fix latest issues pls

**Comment by bf-tom** [comment]
Here is missing S in Stakers. Also, the first answer should be correct

![Image](https://github.com/user-attachments/assets/dce7a46a-2392-4461-83e5-f871a98b194e)
